### ISSUE TITLE
Answer pack size

### ISSUE THREAD

**Issue by kalmar** [Muxamor/KTIVT_BB_SS#4]
Тут еще проблемка с пакетом ответа. Например посылаю одну команду:

> 00 00 00 01 00 00 00 06 XX XX XX XX XX XX

А в ответ получаю:

> 00 00 00 02 00 00 00 06 XX XX XX XX XX XX

А должно быть:

> 00 00 00 02 00 00 00 04 XX XX XX XX

То есть мне буфер приходит больше, чем должен быть по документации.

**Comment by Muxamor** [comment]
По идее все верно.
Ответ 6 байт и команда 6 байт. Ответ содержит  два байта с  номером  канала и 4 байта ответа на команду. Так должно быть.

**Comment by kalmar** [comment]
Ну тогда это косяк документации получается. Там явного указания размера команд и ответов я не нашел, а из таблицы угадывается 6 и 4, соответственно. Напишу тогда Александру, чтоб документацию поправил.

**Comment by Muxamor** [comment]
OK
