### ISSUE TITLE
Номер пакета совпадает с меткой времени

### ISSUE THREAD

**Issue by kalmar** [Muxamor/KTIVT_BB_SS#5]
Еще вопрос) У меня в пакетах с данными метка времени совпадает с номером пакета. То есть за первую секунду мне приходят 3 пакета, и у всех номер 1. В следующую секунду приходят 3 пакета с номером 2. Можно сделать так, чтоб номера приходящих пакетов шли по порядку?

**Comment by Muxamor** [comment]
Эти три пакета приходят с трех каналов раз в секунду. Номер пакета определяет количество пакетов с канала, и по этому номеру мы определяем были ли пропуски в канале. Метка времени при определенных условиях может не совпадать с номером пакета. 
В пакете есть номер  канала можно привязаться к нему и тогда канальные пакеты будут по порядку.
Так же нужно иметь ввиду что пакеты могут приходить не всегда в порядке первый пакет первый канал второй пакет 2 канал  третий пакет 3 канал, а в произвольном порядке.

**Comment by kalmar** [comment]
Ну ладно тогда.
