### ISSUE TITLE
Команда 000114000000 подвешивает железку

### ISSUE THREAD

**Issue by kalmar** [Muxamor/KTIVT_BB_SS#6]
При стении ID канала программа подвисает навсегда.
Лог с железки:

>  Got command parcel from Eth
>  Size command parcel from Eth: 6
>  Receive from eth  command: 0x00 0x01 0x14 0x00 0x00 0x00  
> ^C
> root@beaglebone:/kti_bb_ss#

**Comment by Muxamor** [comment]
Solved
